modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Achilleus-1/Akis-NeoThunderingImmersed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://linktr.ee/achilleus_"
logoFile="assets/achilleus/achilleus-logo-white.png"
authors="${mod_authors}"
credits="netcatgirl, original Immersive Thunder"
description='''Product of Achilleus.
https://linktr.ee/achilleus_

Distance-based thunder sounds. NeoForge 1.21.1 port and rebranding by Achilleus, based on Immersive Thunder by netcatgirl.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="immersivethunder.mixins.json"

[[mixins]]
config="immersivethunder.neoforge.mixins.json"
